version: '3.7'
services:
  mysql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=innasmir
      - POSTGRES_PASSWORD=123qwerty